-- Core dependency plugins (required by other plugins at load time)
vim.pack.add({ 'https://github.com/nvim-lua/plenary.nvim' })
vim.pack.add({ 'https://github.com/MunifTanjim/nui.nvim' })
vim.pack.add({ 'https://github.com/tpope/vim-fugitive' })
vim.pack.add({ 'https://github.com/nvim-mini/mini.icons' })
