-- which-key.nvim
local wk = require('which-key')

wk.setup({
    preset = 'helix',
    icons = {
        mappings = vim.g.have_nerd_font,
        keys = vim.g.have_nerd_font and {} or {
            Up = '<Up> ',
            Down = '<Down> ',
            Left = '<Left> ',
            Right = '<Right> ',
            C = '<C-…> ',
            M = '<M-…> ',
            D = '<D-…> ',
            S = '<S-…> ',
            CR = '<CR> ',
            Esc = '<Esc> ',
            ScrollWheelDown = '<ScrollWheelDown> ',
            ScrollWheelUp = '<ScrollWheelUp> ',
            NL = '<NL> ',
            BS = '<BS> ',
            Space = '<Space> ',
            Tab = '<Tab> ',
            F1 = '<F1>',
            F2 = '<F2>',
            F3 = '<F3>',
            F4 = '<F4>',
            F5 = '<F5>',
            F6 = '<F6>',
            F7 = '<F7>',
            F8 = '<F8>',
            F9 = '<F9>',
            F10 = '<F10>',
            F11 = '<F11>',
            F12 = '<F12>',
        },
    },
    spec = {
        { '<leader>b', group = 'Buffer' },
        { '<leader>s', group = 'Search' },
        { '<leader>g', group = 'Git' },
        { '<leader>u', group = 'UI / Toggles' },
        { '<leader>w', group = 'Sessions' },
        { '<leader>t', group = 'Terminal' },
        { '<leader>l', group = 'Plugins' },
        { '<leader>e', group = 'Explorer' },
        { '<leader>q', group = 'Quickfix' },
        { '<leader>h', group = 'Git [H]unk',  mode = { 'n', 'v' } },
        { 'gs',        group = 'Surround',    mode = { 'n', 'x' } },
        { 'gr',        group = 'LSP Actions', mode = { 'n' } },
    },
    win = {
        wo = {
            winblend = 100,
        },
    },
})
